version: 1.1.0.{build}.{branch}

nuget:
  account_feed: false
  
init:
  - git config --global core.autocrlf true
  
before_build:
 - cmd: dotnet restore TagHelperSamples\TagHelperSamples.sln

build_script:
 - cmd: dotnet build TagHelperSamples\src\TagHelperSamples.Bootstrap
 - cmd: dotnet build TagHelperSamples\src\TagHelperSamples.Markdown
 - cmd: dotnet build TagHelperSamples\src\TagHelperSamples.Markdown.Tests
 - cmd: dotnet build TagHelperSamples\src\TagHelperSamples.Web
 
test_script:
 - ps: cd .\TagHelperSamples\src\TagHelperSamples.Markdown.Tests
 - cmd: dotnet test 